language: cpp
compiler: 
- gcc

os:
- linux

script:
- mkdir Release && cd Release && cmake -DCMAKE_BUILD_TYPE=Release .. && make

branches:
  only:
  - master


addons:
  apt:
    packages:
    - cmake-data
    - cmake
    - libsdl2-dev

